{
  "openapi": "3.0.3",
  "info": {
    "title": "Rental Car Server",
    "description": "Api documentation rental car server",
    "version": "1.0.0",
    "contact": {
      "name": "Rafli Andreansyah",
      "email": "rafliandreansyah957@gmail.com",
      "url": "https://www.linkedin.com/in/rafli-andreansyah-86299217a"
    }
  },
  "servers": [
    {
      "url": "https://{env}:{port}/api/{version}",
      "description": "Server developer rental car",
      "variables": {
        "env": {
          "description": "Environtment url",
          "default": "localhost",
          "enum": [
            "localhost"
          ]
        },
        "port": {
          "description": "port server rental car",
          "default": "8080",
          "enum": [
            "8080",
            "8081"
          ]
        },
        "version": {
          "description": "api version",
          "default": "v1",
          "enum": [
            "v1"
          ]
        }
      }
    }
  ],
  "paths": {
    "/auth/authenticate": {
      "post": {
        "description": "end point for a authentication user",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "email": {
                    "type": "string",
                    "required": true
                  },
                  "password": {
                    "type": "string",
                    "required": true
                  }
                }
              },
              "examples": {
                "login": {
                  "summary": "request login",
                  "value": {
                    "email": "test@gmail.com",
                    "password": "secure"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success login",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": {
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/UserNotFoundError"
          },
          "401": {
            "description": "invalid email or password",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "not found": {
                    "value": {
                      "status": 401,
                      "error": "Invalid email or password",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/reset": {
      "post": {
        "description": "end point for reset password",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "email": {
                    "type": "string",
                    "required": true
                  }
                }
              },
              "examples": {
                "reset": {
                  "value": {
                    "email": "reset@gmail.com"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "response success send reset password to email",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": {
                        "message": "Send link reset password success. Please check your email message to reset password"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/UserNotFoundError"
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "description": "Registration new user",
        "tags": [
          "Authentication"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/GeneralResponseWithDataObject"
              },
              "examples": {
                "register": {
                  "value": {
                    "email": "email@mail.com",
                    "password": "secretpassword",
                    "name": "alexandre",
                    "phone": "+6281232720821"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "response register success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "description": "register success example",
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": "success register"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "error validation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "bad request": {
                    "value": {
                      "status": 400,
                      "error": "format email not valid",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "error when user already registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "conflict": {
                    "value": {
                      "status": 409,
                      "error": "user with this email already registered",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "get list of users",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "name": "role",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "is_active",
            "in": "query",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success response get list users",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataArrayObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": [
                        {
                          "id": "0092HSH-0092HSH",
                          "image_url": "https://user-profilerafli.com",
                          "name": "rafli a",
                          "phone": "+62039477755",
                          "is_active": "true"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      },
      "post": {
        "description": "create data users",
        "tags": [
          "Users"
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "required": true,
                    "type": "string"
                  },
                  "password": {
                    "required": true,
                    "type": "string"
                  },
                  "name": {
                    "required": true,
                    "type": "string"
                  },
                  "phone": {
                    "required": true,
                    "type": "string"
                  },
                  "role": {
                    "required": true,
                    "type": "string"
                  },
                  "dob": {
                    "description": "timestamp",
                    "required": false,
                    "type": "number"
                  },
                  "image": {
                    "required": false,
                    "type": "array",
                    "items": {
                      "format": "binary",
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success create user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 201,
                      "error": null,
                      "data": {
                        "id": "00KDD-7DDH8-KKS88",
                        "name": "rafli andreansyah",
                        "email": "rafli@gmail.com",
                        "image_url": null,
                        "dob": null,
                        "phone": "081232720999",
                        "role": "user",
                        "is_active": true
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "409": {
            "description": "error when user already registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "conflict": {
                    "value": {
                      "status": 409,
                      "error": "user with this email already registered",
                      "data": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "description": "get detail user by id",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "response success get detail users",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": {
                        "id": "8DJS-KWME-DMWA-MDMM",
                        "name": "suprianto alexandre",
                        "image_url": "https://media.istockphoto.com/id/1386479313/photo/happy-millennial-afro-american-business-woman-posing-isolated-on-white.webp?b=1&s=170667a&w=0&k=20&c=ahypUC_KTc95VOsBkzLFZiCQ0VJwewfrSV43BOrLETM=",
                        "dob": "1996-12-20",
                        "phone": "+6289373622",
                        "is_active": "true",
                        "role": "USER",
                        "date_created": "2023-10-30"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/UserNotFoundError"
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      },
      "delete": {
        "description": "delete user by id",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success delete user data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataString"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": "200",
                      "error": null,
                      "data": "success delete data user"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/UserNotFoundError"
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      },
      "patch": {
        "description": "patch user data",
        "tags": [
          "Users"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "phone": {
                    "type": "string"
                  },
                  "image": {
                    "type": "array",
                    "items": {
                      "format": "binary"
                    }
                  },
                  "dob": {
                    "type": "string"
                  },
                  "is_active": {
                    "description": "only role admin",
                    "type": "string"
                  },
                  "role": {
                    "description": "only role admin",
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success edit user",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": {
                        "id": "00AAS-83JJD-00AAS-83JJD",
                        "name": "081232720888",
                        "image": "https://imageprofile0837ssss",
                        "dob": null,
                        "is_active": true,
                        "role": "USER"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/UserNotFoundError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      }
    },
    "/users/{id}/transactions": {
      "get": {
        "description": "get list transaction by user id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "tags": ["Users"],
        "responses": {
          "200": {
            "description": "success get list transaction by user id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataArrayObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": [
                        {
                          "id": "0JJS8-884JN-MMMS8-KKSK0",
                          "no_invoice": "trx-snn89920mmdsm",
                          "start_date": "2022-10-25T10:00:00",
                          "end_date": "2022-10-26T10:00:00",
                          "duration": 1,
                          "car_name": "pajero",
                          "brand": "mitsubishi",
                          "total_price": 300000.00,
                          "status": "finish"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          },
          "404": {
            "$ref": "#/components/responses/UserNotFoundError"
          }
        }
      }
    },
    "/cars": {
      "get": {
        "description": "get list of cars",
        "tags": [
          "Cars"
        ],
        "parameters": [
          {
            "name": "start_date_rent",
            "in": "query",
            "description": "required for role user",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "duration",
            "in": "query",
            "description": "required for role user",
            "schema": {
              "type": "number"
            }
          },
          {
            "name": "order_by_date_created",
            "in": "query",
            "description": "only admin can access",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "transactions",
            "in": "query",
            "description": "onlu admin can access",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "success get list car",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataArrayObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": [
                        {
                          "id": "00FYY-66DYY-666DH",
                          "name": "Toyota Fortuner",
                          "image_url": "https://fortunerfjjs888s.com",
                          "year": 2020,
                          "transmission": "Automatic",
                          "price": 250000.00
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      },
      "post": {
        "description": "create data cars and only admin can create",
        "tags": [
          "Cars"
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/RequestPostAndPutCars"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "success create car",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 201,
                      "error": null,
                      "data": {
                        "id": "0KDD2-HJSK9-KKS00-23KSS",
                        "name": "Pajero",
                        "image": "https://pajero.com",
                        "image_detail": [
                          {
                            "id": "DD23S-KDSKJ-99DUS",
                            "image": "https://pajero1.com"
                          }
                        ],
                        "brand": "mitsubishi",
                        "year": 2022,
                        "capacity": 7,
                        "cc": 2000,
                        "price": 300000.00,
                        "description": "this is description car",
                        "transmission": "automatic",
                        "tax": 0,
                        "discount": 0,
                        "is_active": true
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      }
    },
    "/cars/{id}": {
      "get": {
        "description": "get car data by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "tags": [
          "Cars"
        ],
        "responses": {
          "200": {
            "description": "success get data car",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": {
                        "id": "00JS8-77SHS-88JJJ-UHH77-2DSSA",
                        "name": "Avanza",
                        "image": "https://avanza.com",
                        "brand": "Toyota",
                        "year": 2020,
                        "capacity": 6,
                        "cc": 1500,
                        "price_per_day": 250000.00,
                        "tax": null,
                        "discount": null,
                        "description": "description of avanza",
                        "transmission": "automatic",
                        "is_active": true
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/CarNotFoundError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      },
      "delete": {
        "description": "delete car data by id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "tags": [
          "Cars"
        ],
        "responses": {
          "200": {
            "description": "success delete car data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataString"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": "success delete car"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/CarNotFoundError"
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      },
      "patch": {
        "description": "edit car data by id",
        "tags": [
          "Cars"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/RequestPostAndPutCars"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success edit cars",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GeneralResponseWithDataObject"
                },
                "examples": {
                  "success": {
                    "value": {
                      "status": 200,
                      "error": null,
                      "data": {
                        "id": "00JS8-77SHS-88JJJ-UHH77-2DSSA",
                        "name": "Avanza",
                        "image": "https://avanza.com",
                        "brand": "Toyota",
                        "year": 2020,
                        "capacity": 6,
                        "cc": 1500,
                        "price_per_day": 250000.00,
                        "tax": null,
                        "discount": null,
                        "description": "description of avanza",
                        "transmission": "automatic",
                        "is_active": true
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "$ref": "#/components/responses/AccessForbiddenError"
          },
          "404": {
            "$ref": "#/components/responses/CarNotFoundError"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedError"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GeneralResponseWithDataObject": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "object"
          }
        }
      },
      "GeneralResponseWithDataArrayObject": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        }
      },
      "GeneralResponseWithDataString": {
        "type": "object",
        "properties": {
          "status": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "data": {
            "type": "string"
          }
        }
      },
      "RequestPostAndPutCars": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "required": true
          },
          "image": {
            "type": "array",
            "required": true,
            "items": {
              "format": "binary",
              "type": "string"
            }
          },
          "image_detail": {
            "type": "array",
            "required": false,
            "items": {
              "format": "binary",
              "type": "string"
            }
          },
          "brand": {
            "type": "string",
            "required": true
          },
          "year": {
            "type": "number",
            "required": true
          },
          "capacity": {
            "type": "number",
            "required": true
          },
          "cc": {
            "type": "number",
            "required": true
          },
          "price": {
            "type": "number",
            "required": true
          },
          "description": {
            "type": "string",
            "required": true
          },
          "transmission": {
            "type": "string",
            "required": true
          },
          "tax": {
            "type": "number",
            "required": false
          },
          "discount": {
            "type": "number",
            "required": false
          }
        }
      }
    },
    "responses": {
      "UserNotFoundError": {
        "description": "Response error for user not found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/GeneralResponseWithDataObject"
            },
            "examples": {
              "error": {
                "value": {
                  "status": 404,
                  "error": "user doesn't exist",
                  "data": null
                }
              }
            }
          }
        }
      },
      "CarNotFoundError": {
        "description": "Response error for car not found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/GeneralResponseWithDataObject"
            },
            "examples": {
              "error": {
                "value": {
                  "status": 404,
                  "error": "car doesn't exist",
                  "data": null
                }
              }
            }
          }
        }
      },
      "AccessForbiddenError": {
        "description": "response error forbidden access",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/GeneralResponseWithDataArrayObject"
            },
            "examples": {
              "forbidden": {
                "value": {
                  "status": 403,
                  "error": "access forbidden to access this data",
                  "data": null
                }
              }
            }
          }
        }
      },
      "UnauthorizedError": {
        "description": "response error forbidden access",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/GeneralResponseWithDataArrayObject"
            },
            "examples": {
              "unauthorized": {
                "value": {
                  "status": 401,
                  "error": "authorization required",
                  "data": null
                }
              }
            }
          }
        }
      }
    }
  }
}
